import img1 from "../assets/images/sapiens.jpg"
import img2 from "../assets/images/guens.jpg"
import img3 from "../assets/images//silk-roads.jpg"
import img4 from "../assets/images/usa.jpg"
import img5 from "../assets/images/prince.jpg"
import img6 from "../assets/images/art-war.jpg"
import img7 from "../assets/images/the-communist.jpg"
import img8 from "../assets/images/republic.jpg"
import img9 from "../assets/images/bible.jpg"
import img10 from "../assets/images/Al-Quran.jpg"
import img11 from "../assets/images/baghavad.jpg"
import img12 from "../assets/images/Tao-te.jpg"
import img13 from "../assets/images/thin-king.jpg"
import img14 from "../assets/images/men's.jpg"
import img15 from "../assets/images/power.jpg"
import img16 from "../assets/images/Emotional-Intelligence.jpg"
import img17 from "../assets/images/img17.png"
import logo from "../assets/images/ALMAARIFA.webp"
import profile from "../assets/images/profile.jpg"
import bg from "../assets/images/library books.jpg"

export default {img1,img10,img11,img12,img13,img14,img15,img16,img17,img2,img3,img4,img5,img6,img7,img8,img9,logo,profile,bg}